PRODUCT_VERSION_MAJOR = 15
PRODUCT_VERSION_MINOR = 0

# Internal version
WITAQUA_VERSION := WitAqua-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date +%Y%m%d)-$(LINEAGE_BUILD)-v$(WITAQUA_VERSION)

# Display version
LINEAGE_DISPLAY_VERSION := WitAqua-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_BUILD)-v$(WITAQUA_VERSION)
